name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: casiez/turbotouchpredictor

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make

